# Generated by Django 5.0.6 on 2024-06-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='id',
            new_name='roomNo',
        ),
    ]
