# Generated by Django 5.0.6 on 2024-06-08 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_id_room_roomno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotels',
        ),
        migrations.AlterField(
            model_name='room',
            name='roomNo',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
